\set ON_ERROR_STOP on

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
  :'development_role'
)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'development_role'
) \gexec

SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 10',
  :'development_role',
  :'development_password'
) \gexec

SELECT format('ALTER ROLE %I SET search_path TO public', :'development_role') \gexec

SELECT format(
  'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
  :'test_role'
)
WHERE NOT EXISTS (
  SELECT 1 FROM pg_roles WHERE rolname = :'test_role'
) \gexec

SELECT format(
  'ALTER ROLE %I WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 10',
  :'test_role',
  :'test_password'
) \gexec

SELECT format('ALTER ROLE %I SET search_path TO public', :'test_role') \gexec
